#!/usr/bin/env bash
#

IMAGE="yolo_devcontainer:swift"
_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

unset API_KEY API_ENDPOINT
export API_KEY="🔥🔥🔥"
export API_ENDPOINT="https://api.z.ai/api/anthropic"

"$_dir/openloop_cc_docker-base" "$IMAGE" "-z" "$@"
