#!/usr/bin/env bash
#
# ywa - yolo-wait-anthropic (interactive): Claude code with Anthropic as inference provider
#

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

CONTAINER_NAME="ywa"
IMAGE="yolo_devcontainer"
source "$SCRIPT_DIR/y"
