#!/usr/bin/env bash
#
# ywz - yolo-wait-z (interactive): Claude code with z API as inference provider
#

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

CONTAINER_NAME="ywz"
IMAGE="yolo_devcontainer"
source "$SCRIPT_DIR/y-z"
